// apps/react-mfe/src/App.tsx
import { useSignals } from '@preact/signals-react/runtime'
import { isAuthenticated, currentUser, isRefreshing, authError, login, logout } from '@mfe-demo/domain'
import { apiLogin, apiLogout, apiGetDashboard } from './api'
import { useState, useEffect } from 'react'

// ─── Login Page ──────────────────────────────────────────────────────────────
function LoginPage() {
  useSignals()
  const [email, setEmail]       = useState('venki@mfe-demo.com')
  const [password, setPassword] = useState('demo123')
  const [loading, setLoading]   = useState(false)
  const [error, setError]       = useState<string | null>(null)

  async function handleLogin(e: React.FormEvent) {
    e.preventDefault()
    setLoading(true)
    setError(null)
    try {
      const data = await apiLogin(email, password)
      login(data.user, { accessToken: data.accessToken, refreshToken: data.refreshToken })
    } catch {
      setError('Invalid credentials. Try venki@mfe-demo.com / demo123')
    } finally {
      setLoading(false)
    }
  }

  return (
    <div style={styles.page}>
      <div style={styles.loginCard}>
        <div style={styles.badge}>React MFE</div>
        <h1 style={styles.title}>Auth Store<br /><span style={styles.titleAccent}>Demo</span></h1>
        <p style={styles.subtitle}>Part 4 — Enterprise MFE Architecture</p>

        <form onSubmit={handleLogin} style={styles.form}>
          <div style={styles.field}>
            <label style={styles.label}>Email</label>
            <input
              style={styles.input}
              type="email"
              value={email}
              onChange={e => setEmail(e.target.value)}
              placeholder="venki@mfe-demo.com"
            />
          </div>
          <div style={styles.field}>
            <label style={styles.label}>Password</label>
            <input
              style={styles.input}
              type="password"
              value={password}
              onChange={e => setPassword(e.target.value)}
              placeholder="demo123"
            />
          </div>
          {error && <p style={styles.error}>{error}</p>}
          <button style={loading ? styles.btnDisabled : styles.btn} type="submit" disabled={loading}>
            {loading ? 'Authenticating...' : 'Login →'}
          </button>
        </form>

        <div style={styles.hint}>
          <p style={styles.hintTitle}>🧪 Demo Credentials</p>
          <code style={styles.code}>venki@mfe-demo.com / demo123</code><br />
          <code style={styles.code}>react@mfe-demo.com / demo123</code>
        </div>
      </div>
    </div>
  )
}

// ─── Dashboard ───────────────────────────────────────────────────────────────
function Dashboard() {
  useSignals()
  const user      = currentUser.value
  const refreshing = isRefreshing.value
  const [stats, setStats]   = useState<any>(null)
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    apiGetDashboard()
      .then(setStats)
      .catch(console.error)
      .finally(() => setLoading(false))
  }, [])

  async function handleLogout() {
    const storedToken = localStorage.getItem('refreshToken')
    if (storedToken) await apiLogout(storedToken)
    localStorage.removeItem('refreshToken')
    logout()
  }

  return (
    <div style={styles.page}>
      <div style={styles.dashboard}>
        <header style={styles.header}>
          <div style={styles.userInfo}>
            <img src={user?.avatar} alt={user?.name} style={styles.avatar} />
            <div>
              <p style={styles.userName}>{user?.name}</p>
              <p style={styles.userEmail}>{user?.email}</p>
            </div>
          </div>
          <div style={styles.headerRight}>
            <div style={styles.badge}>React MFE</div>
            <button onClick={handleLogout} style={styles.logoutBtn}>Logout</button>
          </div>
        </header>

        {refreshing && (
          <div style={styles.refreshBanner}>
            🔄 Token refreshing... (single controlled call, no storm)
          </div>
        )}

        <div style={styles.storeViz}>
          <h2 style={styles.sectionTitle}>📡 Domain Signal State</h2>
          <div style={styles.signalGrid}>
            <SignalCard label="isAuthenticated" value={String(isAuthenticated.value)} positive />
            <SignalCard label="currentUser" value={user?.name ?? 'null'} positive />
            <SignalCard label="isRefreshing" value={String(refreshing)} />
            <SignalCard label="authError" value={authError.value ?? 'null'} />
          </div>
          <p style={styles.note}>
            ↑ These are <strong>@preact/signals-core</strong> computed values consumed via{' '}
            <code>useSignals()</code> — no useState, no props, no context.
          </p>
        </div>

        {loading ? (
          <div style={styles.loading}>Loading dashboard data...</div>
        ) : stats ? (
          <div style={styles.statsGrid}>
            <StatCard icon="🧩" label="MFEs Running" value={stats.stats.mfesRunning} />
            <StatCard icon="⚡" label="Signals Active" value={stats.stats.signalsActive} />
            <StatCard icon="🔑" label="Token Expiry" value={stats.stats.tokenExpiresIn} />
            <StatCard icon="🕐" label="Last Refresh" value={new Date(stats.stats.lastRefresh).toLocaleTimeString()} />
          </div>
        ) : null}

        <div style={styles.archNote}>
          <h3 style={styles.archTitle}>🏗 What's happening under the hood</h3>
          <ul style={styles.archList}>
            <li>Auth store lives in <code>@mfe-demo/domain</code> — outside React</li>
            <li>React consumes signals via <code>useSignals()</code> from <code>@preact/signals-react</code></li>
            <li>Token refresh uses singleton promise — fires exactly once even if called concurrently</li>
            <li>Logout triggers global reset across all registered stores</li>
            <li>Angular MFE (port 4200) shares the same domain store</li>
          </ul>
        </div>
      </div>
    </div>
  )
}

// ─── Sub-components ──────────────────────────────────────────────────────────
function SignalCard({ label, value, positive }: { label: string; value: string; positive?: boolean }) {
  return (
    <div style={styles.signalCard}>
      <p style={styles.signalLabel}>{label}</p>
      <p style={{ ...styles.signalValue, color: positive ? '#34d399' : '#94a3b8' }}>{value}</p>
    </div>
  )
}

function StatCard({ icon, label, value }: { icon: string; label: string; value: any }) {
  return (
    <div style={styles.statCard}>
      <span style={styles.statIcon}>{icon}</span>
      <p style={styles.statValue}>{value}</p>
      <p style={styles.statLabel}>{label}</p>
    </div>
  )
}

// ─── Root App ────────────────────────────────────────────────────────────────
export default function App() {
  useSignals()
  return isAuthenticated.value ? <Dashboard /> : <LoginPage />
}

// ─── Styles ──────────────────────────────────────────────────────────────────
const styles: Record<string, React.CSSProperties> = {
  page: {
    minHeight: '100vh',
    background: '#020817',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontFamily: "'DM Mono', 'Fira Code', monospace",
    color: '#e2e8f0',
    padding: '2rem',
  },
  loginCard: {
    background: '#0f172a',
    border: '1px solid #1e293b',
    borderRadius: '16px',
    padding: '3rem',
    width: '100%',
    maxWidth: '440px',
    boxShadow: '0 25px 50px rgba(0,0,0,0.5)',
  },
  badge: {
    display: 'inline-block',
    background: '#0ea5e9',
    color: '#020817',
    fontSize: '0.7rem',
    fontWeight: 700,
    padding: '4px 10px',
    borderRadius: '4px',
    letterSpacing: '0.1em',
    textTransform: 'uppercase' as const,
    marginBottom: '1.5rem',
  },
  title: {
    fontSize: '2.5rem',
    fontWeight: 800,
    lineHeight: 1.1,
    margin: '0 0 0.5rem',
    color: '#f8fafc',
  },
  titleAccent: { color: '#38bdf8' },
  subtitle: { color: '#475569', fontSize: '0.85rem', margin: '0 0 2rem' },
  form: { display: 'flex', flexDirection: 'column' as const, gap: '1rem' },
  field: { display: 'flex', flexDirection: 'column' as const, gap: '6px' },
  label: { fontSize: '0.75rem', color: '#64748b', letterSpacing: '0.05em' },
  input: {
    background: '#1e293b',
    border: '1px solid #334155',
    borderRadius: '8px',
    padding: '0.75rem 1rem',
    color: '#f8fafc',
    fontSize: '0.9rem',
    fontFamily: 'inherit',
    outline: 'none',
  },
  btn: {
    background: '#38bdf8',
    color: '#020817',
    border: 'none',
    borderRadius: '8px',
    padding: '0.85rem',
    fontSize: '0.9rem',
    fontWeight: 700,
    cursor: 'pointer',
    marginTop: '0.5rem',
    fontFamily: 'inherit',
    letterSpacing: '0.05em',
  },
  btnDisabled: {
    background: '#1e293b',
    color: '#475569',
    border: 'none',
    borderRadius: '8px',
    padding: '0.85rem',
    fontSize: '0.9rem',
    fontFamily: 'inherit',
    cursor: 'not-allowed',
    marginTop: '0.5rem',
  },
  error: { color: '#f87171', fontSize: '0.8rem', margin: 0 },
  hint: {
    marginTop: '2rem',
    padding: '1rem',
    background: '#0f2137',
    borderRadius: '8px',
    border: '1px solid #1e3a5f',
  },
  hintTitle: { margin: '0 0 0.5rem', fontSize: '0.8rem', color: '#64748b' },
  code: { fontSize: '0.78rem', color: '#38bdf8', fontFamily: 'inherit' },
  dashboard: { width: '100%', maxWidth: '900px' },
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: '2rem',
    background: '#0f172a',
    border: '1px solid #1e293b',
    borderRadius: '12px',
    padding: '1.25rem 1.5rem',
  },
  headerRight: { display: 'flex', alignItems: 'center', gap: '1rem' },
  userInfo: { display: 'flex', alignItems: 'center', gap: '1rem' },
  avatar: { width: 44, height: 44, borderRadius: '50%', background: '#1e293b' },
  userName: { margin: 0, fontWeight: 700, fontSize: '0.95rem' },
  userEmail: { margin: 0, fontSize: '0.78rem', color: '#475569' },
  logoutBtn: {
    background: 'transparent',
    border: '1px solid #334155',
    color: '#94a3b8',
    borderRadius: '6px',
    padding: '6px 14px',
    cursor: 'pointer',
    fontSize: '0.8rem',
    fontFamily: 'inherit',
  },
  refreshBanner: {
    background: '#1c3d5a',
    border: '1px solid #0ea5e9',
    borderRadius: '8px',
    padding: '0.75rem 1rem',
    marginBottom: '1.5rem',
    fontSize: '0.85rem',
    color: '#7dd3fc',
  },
  storeViz: {
    background: '#0f172a',
    border: '1px solid #1e293b',
    borderRadius: '12px',
    padding: '1.5rem',
    marginBottom: '1.5rem',
  },
  sectionTitle: { margin: '0 0 1rem', fontSize: '0.9rem', color: '#94a3b8' },
  signalGrid: { display: 'grid', gridTemplateColumns: 'repeat(2, 1fr)', gap: '0.75rem' },
  signalCard: {
    background: '#1e293b',
    borderRadius: '8px',
    padding: '0.75rem 1rem',
    border: '1px solid #334155',
  },
  signalLabel: { margin: '0 0 4px', fontSize: '0.7rem', color: '#475569', letterSpacing: '0.05em' },
  signalValue: { margin: 0, fontSize: '0.85rem', fontWeight: 600 },
  note: { margin: '1rem 0 0', fontSize: '0.75rem', color: '#475569', lineHeight: 1.6 },
  loading: { textAlign: 'center' as const, padding: '2rem', color: '#475569' },
  statsGrid: {
    display: 'grid',
    gridTemplateColumns: 'repeat(4, 1fr)',
    gap: '1rem',
    marginBottom: '1.5rem',
  },
  statCard: {
    background: '#0f172a',
    border: '1px solid #1e293b',
    borderRadius: '12px',
    padding: '1.25rem',
    textAlign: 'center' as const,
  },
  statIcon: { fontSize: '1.5rem' },
  statValue: { margin: '0.5rem 0 0.25rem', fontWeight: 700, fontSize: '1.1rem', color: '#38bdf8' },
  statLabel: { margin: 0, fontSize: '0.72rem', color: '#475569' },
  archNote: {
    background: '#0f172a',
    border: '1px solid #1e293b',
    borderRadius: '12px',
    padding: '1.5rem',
  },
  archTitle: { margin: '0 0 1rem', fontSize: '0.9rem', color: '#94a3b8' },
  archList: { margin: 0, padding: '0 0 0 1.25rem', display: 'flex', flexDirection: 'column' as const, gap: '0.5rem' },
}

// apps/angular-mfe/src/app.component.ts
import {
  Component,
  ChangeDetectionStrategy,
  signal,
  OnInit,
} from '@angular/core'
import { CommonModule } from '@angular/common'
import { FormsModule } from '@angular/forms'
import {
  isAuthenticated,
  currentUser,
  isRefreshing,
  authError,
  login,
  logout,
} from '@mfe-demo/domain'
import { toAngularSignal } from './utils/to-angular-signal'
import { apiLogin, apiLogout, apiGetDashboard } from './api'

// ─── Login Component ─────────────────────────────────────────────────────────
@Component({
  selector: 'app-login',
  standalone: true,
  imports: [CommonModule, FormsModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="page">
      <div class="card">
        <span class="badge">Angular MFE</span>
        <h1 class="title">Auth Store<br /><span class="accent">Demo</span></h1>
        <p class="subtitle">Part 4 — Enterprise MFE Architecture</p>

        <div class="form">
          <div class="field">
            <label class="label">Email</label>
            <input class="input" type="email" [(ngModel)]="email" placeholder="venki@mfe-demo.com" />
          </div>
          <div class="field">
            <label class="label">Password</label>
            <input class="input" type="password" [(ngModel)]="password" placeholder="demo123" />
          </div>
          @if (error()) {
            <p class="error">{{ error() }}</p>
          }
          <button class="btn" [disabled]="loading()" (click)="handleLogin()">
            {{ loading() ? 'Authenticating...' : 'Login →' }}
          </button>
        </div>

        <div class="hint">
          <p class="hint-title">🧪 Demo Credentials</p>
          <code>venki&#64;mfe-demo.com / demo123</code><br />
          <code>react&#64;mfe-demo.com / demo123</code>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .page { min-height:100vh; background:#020817; display:flex; align-items:center; justify-content:center; font-family:'DM Mono','Fira Code',monospace; color:#e2e8f0; padding:2rem; }
    .card { background:#0f172a; border:1px solid #1e293b; border-radius:16px; padding:3rem; width:100%; max-width:440px; box-shadow:0 25px 50px rgba(0,0,0,.5); }
    .badge { display:inline-block; background:#a78bfa; color:#020817; font-size:.7rem; font-weight:700; padding:4px 10px; border-radius:4px; letter-spacing:.1em; text-transform:uppercase; margin-bottom:1.5rem; }
    .title { font-size:2.5rem; font-weight:800; line-height:1.1; margin:0 0 .5rem; color:#f8fafc; }
    .accent { color:#a78bfa; }
    .subtitle { color:#475569; font-size:.85rem; margin:0 0 2rem; }
    .form { display:flex; flex-direction:column; gap:1rem; }
    .field { display:flex; flex-direction:column; gap:6px; }
    .label { font-size:.75rem; color:#64748b; letter-spacing:.05em; }
    .input { background:#1e293b; border:1px solid #334155; border-radius:8px; padding:.75rem 1rem; color:#f8fafc; font-size:.9rem; font-family:inherit; outline:none; }
    .btn { background:#a78bfa; color:#020817; border:none; border-radius:8px; padding:.85rem; font-size:.9rem; font-weight:700; cursor:pointer; margin-top:.5rem; font-family:inherit; letter-spacing:.05em; }
    .btn:disabled { background:#1e293b; color:#475569; cursor:not-allowed; }
    .error { color:#f87171; font-size:.8rem; margin:0; }
    .hint { margin-top:2rem; padding:1rem; background:#1a1040; border-radius:8px; border:1px solid #2d1f6e; }
    .hint-title { margin:0 0 .5rem; font-size:.8rem; color:#64748b; }
    code { font-size:.78rem; color:#a78bfa; font-family:inherit; }
  `]
})
export class LoginComponent {
  email    = 'venki@mfe-demo.com'
  password = 'demo123'
  loading  = signal(false)
  error    = signal<string | null>(null)

  async handleLogin() {
    this.loading.set(true)
    this.error.set(null)
    try {
      const data = await apiLogin(this.email, this.password)
      login(data.user, { accessToken: data.accessToken, refreshToken: data.refreshToken })
    } catch {
      this.error.set('Invalid credentials. Try venki@mfe-demo.com / demo123')
    } finally {
      this.loading.set(false)
    }
  }
}

// ─── Dashboard Component ──────────────────────────────────────────────────────
@Component({
  selector: 'app-dashboard',
  standalone: true,
  imports: [CommonModule],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    <div class="page">
      <div class="dashboard">
        <header class="header">
          <div class="user-info">
            <img [src]="user()?.avatar" [alt]="user()?.name" class="avatar" />
            <div>
              <p class="user-name">{{ user()?.name }}</p>
              <p class="user-email">{{ user()?.email }}</p>
            </div>
          </div>
          <div class="header-right">
            <span class="badge">Angular MFE</span>
            <button class="logout-btn" (click)="handleLogout()">Logout</button>
          </div>
        </header>

        @if (refreshing()) {
          <div class="refresh-banner">
            🔄 Token refreshing... (single controlled call — no storm)
          </div>
        }

        <div class="store-viz">
          <h2 class="section-title">📡 Domain Signal State</h2>
          <div class="signal-grid">
            <div class="signal-card">
              <p class="sig-label">isAuthenticated</p>
              <p class="sig-value positive">{{ isAuth() }}</p>
            </div>
            <div class="signal-card">
              <p class="sig-label">currentUser</p>
              <p class="sig-value positive">{{ user()?.name ?? 'null' }}</p>
            </div>
            <div class="signal-card">
              <p class="sig-label">isRefreshing</p>
              <p class="sig-value">{{ refreshing() }}</p>
            </div>
            <div class="signal-card">
              <p class="sig-label">authError</p>
              <p class="sig-value">{{ err() ?? 'null' }}</p>
            </div>
          </div>
          <p class="note">
            ↑ Domain signals bridged via <strong>toAngularSignal()</strong> — zoneless Angular, OnPush,
            DOM updates only when signal changes.
          </p>
        </div>

        @if (stats()) {
          <div class="stats-grid">
            <div class="stat-card"><span class="stat-icon">🧩</span><p class="stat-val">{{ stats().stats.mfesRunning }}</p><p class="stat-label">MFEs Running</p></div>
            <div class="stat-card"><span class="stat-icon">⚡</span><p class="stat-val">{{ stats().stats.signalsActive }}</p><p class="stat-label">Signals Active</p></div>
            <div class="stat-card"><span class="stat-icon">🔑</span><p class="stat-val">{{ stats().stats.tokenExpiresIn }}</p><p class="stat-label">Token Expiry</p></div>
            <div class="stat-card"><span class="stat-icon">🕐</span><p class="stat-val">{{ formatTime(stats().stats.lastRefresh) }}</p><p class="stat-label">Last Refresh</p></div>
          </div>
        }

        <div class="arch-note">
          <h3 class="arch-title">🏗 What's happening under the hood</h3>
          <ul class="arch-list">
            <li>Zoneless Angular — <code>provideExperimentalZonelessChangeDetection()</code></li>
            <li><code>toAngularSignal()</code> bridges domain signals to Angular signals</li>
            <li><code>ChangeDetectionStrategy.OnPush</code> — DOM only updates on signal change</li>
            <li>Same domain store as React MFE (port 5173) — shared singleton brain</li>
            <li>Logout triggers global reset via the reset registry</li>
          </ul>
        </div>
      </div>
    </div>
  `,
  styles: [`
    .page { min-height:100vh; background:#020817; display:flex; align-items:center; justify-content:center; font-family:'DM Mono','Fira Code',monospace; color:#e2e8f0; padding:2rem; }
    .dashboard { width:100%; max-width:900px; }
    .header { display:flex; justify-content:space-between; align-items:center; margin-bottom:2rem; background:#0f172a; border:1px solid #1e293b; border-radius:12px; padding:1.25rem 1.5rem; }
    .header-right { display:flex; align-items:center; gap:1rem; }
    .badge { display:inline-block; background:#a78bfa; color:#020817; font-size:.7rem; font-weight:700; padding:4px 10px; border-radius:4px; letter-spacing:.1em; text-transform:uppercase; }
    .user-info { display:flex; align-items:center; gap:1rem; }
    .avatar { width:44px; height:44px; border-radius:50%; background:#1e293b; }
    .user-name { margin:0; font-weight:700; font-size:.95rem; }
    .user-email { margin:0; font-size:.78rem; color:#475569; }
    .logout-btn { background:transparent; border:1px solid #334155; color:#94a3b8; border-radius:6px; padding:6px 14px; cursor:pointer; font-size:.8rem; font-family:inherit; }
    .refresh-banner { background:#1c1040; border:1px solid #7c3aed; border-radius:8px; padding:.75rem 1rem; margin-bottom:1.5rem; font-size:.85rem; color:#c4b5fd; }
    .store-viz { background:#0f172a; border:1px solid #1e293b; border-radius:12px; padding:1.5rem; margin-bottom:1.5rem; }
    .section-title { margin:0 0 1rem; font-size:.9rem; color:#94a3b8; }
    .signal-grid { display:grid; grid-template-columns:repeat(2,1fr); gap:.75rem; }
    .signal-card { background:#1e293b; border-radius:8px; padding:.75rem 1rem; border:1px solid #334155; }
    .sig-label { margin:0 0 4px; font-size:.7rem; color:#475569; letter-spacing:.05em; }
    .sig-value { margin:0; font-size:.85rem; font-weight:600; color:#94a3b8; }
    .positive { color:#a78bfa !important; }
    .note { margin:1rem 0 0; font-size:.75rem; color:#475569; line-height:1.6; }
    .stats-grid { display:grid; grid-template-columns:repeat(4,1fr); gap:1rem; margin-bottom:1.5rem; }
    .stat-card { background:#0f172a; border:1px solid #1e293b; border-radius:12px; padding:1.25rem; text-align:center; }
    .stat-icon { font-size:1.5rem; }
    .stat-val { margin:.5rem 0 .25rem; font-weight:700; font-size:1.1rem; color:#a78bfa; }
    .stat-label { margin:0; font-size:.72rem; color:#475569; }
    .arch-note { background:#0f172a; border:1px solid #1e293b; border-radius:12px; padding:1.5rem; }
    .arch-title { margin:0 0 1rem; font-size:.9rem; color:#94a3b8; }
    .arch-list { margin:0; padding:0 0 0 1.25rem; display:flex; flex-direction:column; gap:.5rem; font-size:.82rem; color:#64748b; line-height:1.6; }
    code { color:#a78bfa; font-family:inherit; }
  `]
})
export class DashboardComponent implements OnInit {
  // ← toAngularSignal bridges domain signals to Angular — zoneless + OnPush
  isAuth    = toAngularSignal(isAuthenticated)
  user      = toAngularSignal(currentUser)
  refreshing = toAngularSignal(isRefreshing)
  err       = toAngularSignal(authError)
  stats     = signal<any>(null)

  async ngOnInit() {
    const data = await apiGetDashboard()
    this.stats.set(data)
  }

  async handleLogout() {
    await apiLogout('')
    logout()
  }

  formatTime(iso: string) {
    return new Date(iso).toLocaleTimeString()
  }
}

// ─── Root App Component ───────────────────────────────────────────────────────
@Component({
  selector: 'app-root',
  standalone: true,
  imports: [CommonModule, LoginComponent, DashboardComponent],
  changeDetection: ChangeDetectionStrategy.OnPush,
  template: `
    @if (isAuth()) {
      <app-dashboard />
    } @else {
      <app-login />
    }
  `,
})
export class AppComponent {
  isAuth = toAngularSignal(isAuthenticated)
}
